version: "3.1"
services:
  #Customer Microservice
  customer-ms:
    build:
      context: ./customer
    container_name: customer-ms
    ports:
      - "8103:8103"
    depends_on:
      - mongodb_db
    
  mongodb_db:
    image: mongo:latest
    container_name: customer-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: customer-db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
	  
volumes:
 mongodb_data: {}