apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: books-ms
  name: books-ms
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: 3001-tcp
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: books-ms
status:
  loadBalancer: {}
