apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: books-ms
  name: books-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: books-ms
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: books-ms
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://mongo-db:27017/books-db
          image: icts2123/books-service:latest
          name: books-ms
          ports:
            - containerPort: 3001
          resources: {}
      restartPolicy: Always
status: {}
