apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: customers-ms
  name: customers-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customers-ms
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: customers-ms
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-db:27017/customer-db
          image: icts2123/customers-service:latest
          name: customers-ms
          ports:
            - containerPort: 3003
          resources: {}
      restartPolicy: Always
status: {}
