apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: lends-ms
  name: lends-ms
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
    - name: 3002-tcp
      port: 3002
      targetPort: 3002
  selector:
    io.kompose.service: lends-ms
status:
  loadBalancer: {}
