apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: lends-ms
  name: lends-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lends-ms
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: lends-ms
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://mongo-db:27017/books-db
            - name: SQL_DBNAME
              value: lends-db
            - name: SQL_HOST
              value: mysql-db
            - name: SQL_PASSWORD
              value: mysql-password
            - name: SQL_USER
              value: mysql-user
          image: icts2123/lends-service:latest
          name: lends-ms
          ports:
            - containerPort: 3002
          resources: {}
      restartPolicy: Always
status: {}
