apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Minikube\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: mysql-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: lends-db
            - name: MYSQL_PASSWORD
              value: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              value: mysql-root-password
            - name: MYSQL_USER
              value: mysql-user
          image: mysql:latest
          name: mysql-db
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
