name: Customers service build and push tests

on:
  push:
    branches: [feature/services-customers]
  workflow_dispatch:
  
jobs:
  
  build-customer:
    runs-on: ${{matrix.os}}
    strategy:
        max-parallel: 3
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: libraryMicroservicesG4/customers
    steps:
    - uses: actions/checkout@v2
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 customer-mongodb order-postgres kafka" | sudo tee -a /etc/hosts
    - name: Get branch
      id: get_branch
      run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Get the commit SHA
      id: get_commit_sha
      run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short "$GITHUB_SHA")
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0 
      with:
        path: C:\Users\ICTS21-23.255\Desktop\Microservizi\Esame finale\libraryMicroservicesG4\customers
        dockerfile: C:\Users\ICTS21-23.255\Desktop\Microservizi\Esame finale\libraryMicroservicesG4\customers\Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/customer
        tags: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}-${{ steps.get_branch.outputs.BRANCH }}, latest
        build_args: |
          TAG=${{ steps.get_commit_sha.outputs.COMMIT_SHA }}-${{ steps.get_branch.outputs.BRANCH }}