name: Lends Service build and publish Docker image
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  push_to_registry:
    # If pull request was merged and was from services-lends
    if: (github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'feature/services-lends')
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ vars.DOCKER_HUB_USERNAME }}/lends-service
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./lends
          push: true
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/lends-service:latest
          labels: ${{ steps.meta.outputs.labels }}
